version: "3.7"

services:
  consul-client1:
    image: hashicorp/consul:1.13.1
    container_name: consul-client1
    restart: always
    volumes:
      - ./config:/consul/config
    networks:
      - consul
    ports:
      - "${IP_ADDRESS}:8500:8500"
      - "${IP_ADDRESS}:8600:8600/tcp"
      - "${IP_ADDRESS}:8600:8600/udp"
      - "${IP_ADDRESS}:8301:8301"
      - "${IP_ADDRESS}:8300:8300"
      - "${IP_ADDRESS}:8302:8302"
    command: "agent"

  node-exporter-controller:
    image: prom/node-exporter:latest
    container_name: node-exporter-controller
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    ports:
      - "${IP_ADDRESS}:9100:9100"
    networks:
      - consul

networks:
  consul:
    driver: bridge
